spring.application.name=email-writer-sb
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

gemini.api.key=AQ.Ab8RN6INcUUvq3x2JvdE-D0vFuQIgtsMw47MKi4sqe68xr4v5w
